service: serverless-api

plugins:
  - serverless-bundle

package:
  individually: true

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: eu-north-1

functions:
  myFunction:
    handler: functions/myFunction.main
    events:
      - http:
          path: myfunction
          method: get
