service: serverless-api

plugins:
  - serverless-bundle
  - '@severi/serverless-stack-output'

custom:
  stage: ${opt:stage, self:provider.stage}
  output:
    file: .stack.${self:custom.stage}.react_app # using our custom .react_app -format here

package:
  individually: true

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: eu-north-1

functions:
  myFunction:
    handler: functions/myFunction.main
    events:
      - http:
          path: myfunction
          method: get
          cors: true
